package com.karavel.batch.seo.linking.configuration.linking.rules.opodoo;

import com.karavel.batch.seo.linking.common.beans.LinkZTType;
import com.karavel.batch.seo.linking.common.beans.SitesEnum;
import com.karavel.batch.seo.linking.common.GenerationType;
import com.karavel.batch.seo.linking.configuration.linking.beans.LinkingRules;
import com.karavel.batch.seo.linking.configuration.linking.beans.builder.LinkingRuleBuilder;
import com.karavel.batch.seo.linking.configuration.linking.beans.builder.LinkingZTConfigurationRuleBuilder;
import com.karavel.batch.seo.linking.configuration.linking.beans.builder.LinkingZTTypeRuleBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration("LinkingRulesFpSurFpOpodooConfiguration")
public class LinkingRulesFpSurFpOpodoo {


    @Bean
    LinkingRules linkingRulesFpSurFpOpodo() {
        return LinkingRuleBuilder.init()
                .forZoneLevel(7)
                .forSite(SitesEnum.OPODO)
                .forGenerationType(GenerationType.FP)
                .addRule(
                        LinkingZTConfigurationRuleBuilder.init()
                                .withNumber(15)
                                .withLevel(7)
                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                .withLevelZt(6)
                                .withRemoteRule(LinkingZTConfigurationRuleBuilder.init()
                                        .withLevel(7)
                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                .withLevelZt(6)
                                                .build()
                                        )
                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                                .withLevelZt(5)
                                                .build()
                                        )
                                        .withRemoteRule(LinkingZTConfigurationRuleBuilder.init()
                                                .withLevel(7)
                                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                        .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                        .withLevelZt(5)
                                                        .build()
                                                )
                                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                        .withLinkZTType(LinkZTType.SAME_ZTn)
                                                        .withLevelZt(4)
                                                        .build()
                                                )
                                                .withRemoteRule(LinkingZTConfigurationRuleBuilder.init()
                                                        .withLevel(7)
                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                                .withLevelZt(4)
                                                                .build()
                                                        )
                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                                                .withLevelZt(3)
                                                                .build()
                                                        )
                                                        .withRemoteRule(
                                                                LinkingZTConfigurationRuleBuilder.init()
                                                                        .withLevel(7)
                                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                                                .withLevelZt(3)
                                                                                .build()
                                                                        )
                                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                                                                .withLevelZt(2)
                                                                                .build()
                                                                        )
                                                                        .withRemoteRule(
                                                                                LinkingZTConfigurationRuleBuilder.init()
                                                                                        .withLevel(7)
                                                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                                                                .withLevelZt(2)
                                                                                                .build()
                                                                                        )
                                                                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                                                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                                                                                .withLevelZt(1)
                                                                                                .build()
                                                                                        ).build()
                                                                        ).build()
                                                        ).build()
                                                ).build()
                                        ).build()
                                ).build()
                ).addRule(
                        LinkingZTConfigurationRuleBuilder.init()
                                .withNumber(3)
                                .withLevel(7)
                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                        .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                        .withLevelZt(3)
                                        .build()
                                )
                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                        .withLinkZTType(LinkZTType.SAME_ZTn)
                                        .withLevelZt(2)
                                        .build()
                                )
                                .withRemoteRule(LinkingZTConfigurationRuleBuilder.init()
                                        .withLevel(7)
                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                                .withLevelZt(2)
                                                .build()
                                        )
                                        .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                                .withLinkZTType(LinkZTType.SAME_ZTn)
                                                .withLevelZt(1)
                                                .build()
                                        ).build()
                                ).build()
                ).addRule(
                        LinkingZTConfigurationRuleBuilder.init()
                                .withNumber(1)
                                .withLevel(7)
                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                        .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                        .withLevelZt(2)
                                        .build()
                                )
                                .withLinkingZTTypeRule(LinkingZTTypeRuleBuilder.init()
                                        .withLinkZTType(LinkZTType.SAME_ZTn)
                                        .withLevelZt(1)
                                        .build()
                                ).build()
                ).addRule(
                        LinkingZTConfigurationRuleBuilder.init()
                                .withNumber(1)
                                .withLevel(7)
                                .withLinkZTType(LinkZTType.DIFFERENT_ZTn)
                                .withLevelZt(1)
                                .build()
                ).build();
    }

}
